### PR TITLE
Disabled clusters can't change their status

### LINKED ISSUE #491: Clusters which are disabled should not change status to `pending_reconciliation`
**Description**

When a cluster is disabled, an update from KEB should not enable the cluster again. The new created cluster should also be disabled until it gets enabled again by SRE.

**Expected result**

When a cluster is disabled but a new cluster version gets created caused by a cluster update from KEB, the new cluter version should also be in state `disabled`.

**Actual result**

KEB updates are creating new cluster versions which are initailly in state `pending`.

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by clebs**
Fixes #491

### CODE REVIEW

File: pkg/cluster/inventory.go [hunk 1]
```diff
@@ -209,6 +209,9 @@ func (i *DefaultInventory) createStatus(configEntity *model.ClusterConfiguration
 			i.Logger.Debugf("No differences found for status of cluster '%s': not creating new database entity", configEntity.RuntimeID)
 			return oldStatusEntity, nil
 		}
+		if oldStatusEntity.Status.IsDisabled() {
+			newStatusEntity.Status = model.ClusterStatusReconcileDisabled
+		}
 	} else if !repository.IsNotFoundError(err) {
```
Comment (tobiscr) [inline pkg/cluster/inventory.go:215]: awesome. that it already.. much shorter as initially expected :D

**Review by tobiscr — APPROVED** [review]
