### PR TITLE
Leverage heartbeat to send processing Duration instead of own endpoint

### LINKED ISSUE #836: The `pre-main-control-plane-reconciler-e2e` pipeline fails temporarily caused by colliding DB-TXs
**Description**

The pipeline `pre-main-control-plane-reconciler-e2e` is failing casued by colliding DB-TXs. Issue is caused by trying to update the same operation twice at the same time in different threads.

This has to be solved by updating the same operation just once:

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e

**Expected result**

No DB-TX collisions are not happening during regular reconciliation runs.

**Actual result**

DB collisions are happening and lead to a flaky reconciliation result.

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by jeremyharisch**
Instead of updating the processingDuration using an own endpoint, the heartbeat is leveraged to also update it. Thus, we do not have two transaction updating the same row in the scheduler_operations table.

Fixes #836

### CODE REVIEW

File: cmd/mothership/mothership/start/http.go [hunk 1]
```diff
@@ -917,6 +892,19 @@ func updateOperationStateAndRetryID(o *Options, schedulingID, correlationID, ret
 	return err
 }
 
+func updateOperationStateAndRetryIDAndProcessingDuration(o *Options, schedulingID, correlationID, retryID string, state model.OperationState, processingDuration int, reason ...string) error {
+	err := updateOperationStateAndProcessingDuration(o, schedulingID, correlationID, state, processingDuration, reason...)
+	if err != nil {
+		return err
+	}
+	err = o.Registry.ReconciliationRepository().UpdateOperationRetryID(schedulingID, correlationID, retryID)
```
Comment (tobiscr) [inline cmd/mothership/mothership/start/http.go:900]: Do we need this function? Can't we just add this line also to `updateOperationStateAndProcessingDuration` ?

**Review by tobiscr — CHANGES_REQUESTED** [review]

File: cmd/mothership/mothership/start/http.go (hunk 1 above)
Comment (jeremyharisch) [reply cmd/mothership/mothership/start/http.go:900]: I left it here, since they are dealing with different tables, and ot keep the function names as "short" as possible 😅 
But we could also add it there yes

File: cmd/mothership/mothership/start/http.go [hunk 2]
```diff
@@ -904,6 +855,30 @@ func updateOperationState(o *Options, schedulingID, correlationID string, state
...
+
+		err = rTx.UpdateComponentOperationProcessingDuration(schedulingID, correlationID, processingDuration)
+		if err != nil {
+			o.Logger().Errorf("REST endpoint failed to update operation processingDuration (schedulingID:%s/correlationID:%s) "+
+				"to '%s': %s", schedulingID, correlationID, state, err)
+		}
+		return err
+	}
+	return db.Transaction(o.Registry.Connection(), dbOps, o.Logger())
+}
```
Comment (tobiscr) [inline cmd/mothership/mothership/start/http.go:900]: Refactoring planned in https://github.com/kyma-incubator/reconciler/issues/842

**Review by tobiscr — APPROVED** [review]
